name: ClearChat
author: Glenjendary
main: com.glenjendary.clearchat.Main
version: 0.1
description: Clears chat for players, but not for staff!
commands:
  clearchat:
    usage: /clearchat
    description: Clears chat for players
    aliases: [cc, chatclear, chatc, clearc]
